### ISSUE TITLE
ImportError when using with apispec 1.0.0

### ISSUE THREAD

**Issue by AleksMat** [joeyorlando/flask-restplus-marshmallow#3]
Hi,

Thanks for creating this nice package, I think it is exactly what I need for my project.

However the package seems to work only with `apispec<=0.38.0`. Using your package with newer versions of `apispec` (`0.39.0` or `1.0.0`) raises an import error:
```Python
>>> import flask_restplus_marshmallow
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/flask_restplus_marshmallow/__init__.py", line 2, in <module>
    from .api import Api
  File "/usr/local/lib/python3.6/dist-packages/flask_restplus_marshmallow/api.py", line 3, in <module>
    from .swagger import Swagger
  File "/usr/local/lib/python3.6/dist-packages/flask_restplus_marshmallow/swagger.py", line 2, in <module>
    from apispec.ext.marshmallow.swagger import schema2parameters
ImportError: No module named 'apispec.ext.marshmallow.swagger'
```
I see that they have done quite a few changes in `apispec` lately. Do you plan to support newer versions of `apispec`?

**Comment by terrynguyen255** [comment]
Any news on this?

**Comment by joeyorlando** [comment]
Hi there, thanks for your interest in my project 🙂 This project spawned out of a need for a project at work, I never imagined that it would gain any traction outside of that.

At the moment I don't have enough time to maintain this project. I'm going to mark it as archived, but if someone would like to take over the reigns of maintaining, you are more then welcome 🙏🏼
